/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

/**
 *
 * @author 20112
 */
import Backend.TrainerRole;
import javax.swing.JOptionPane;

public class AddClassWindow extends javax.swing.JFrame {
    private TrainerRole trainerRole;

    /**
     * Creates new form AddClassWindow
     */
    public AddClassWindow(TrainerRole trainerRole) {
        initComponents();
        this.trainerRole = trainerRole;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new java.awt.Label();
        IDText1 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        addBtn1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        IDText = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        nameText = new javax.swing.JTextField();
        trainerIdLbl = new java.awt.Label();
        TrainerIdText = new javax.swing.JTextField();
        durationLbl = new java.awt.Label();
        durationText = new javax.swing.JTextField();
        maxPartLbl = new java.awt.Label();
        maxPartText = new javax.swing.JTextField();
        addBtn2 = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(204, 255, 204));
        label2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label2.setText("Class ID");

        IDText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDText1ActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 0, 0));
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");

        addBtn1.setBackground(new java.awt.Color(0, 0, 0));
        addBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addBtn1.setText("Add");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(204, 255, 204));
        label1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label1.setText("Class ID");

        IDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTextActionPerformed(evt);
            }
        });

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(204, 255, 204));
        label3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label3.setText("Class Name");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        trainerIdLbl.setAlignment(java.awt.Label.CENTER);
        trainerIdLbl.setBackground(new java.awt.Color(204, 255, 204));
        trainerIdLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        trainerIdLbl.setText("Trainer ID");

        TrainerIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainerIdTextActionPerformed(evt);
            }
        });

        durationLbl.setAlignment(java.awt.Label.CENTER);
        durationLbl.setBackground(new java.awt.Color(204, 255, 204));
        durationLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        durationLbl.setText("Duration");

        durationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durationTextActionPerformed(evt);
            }
        });

        maxPartLbl.setAlignment(java.awt.Label.CENTER);
        maxPartLbl.setBackground(new java.awt.Color(204, 255, 204));
        maxPartLbl.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        maxPartLbl.setText("Max Participants");

        maxPartText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxPartTextActionPerformed(evt);
            }
        });

        addBtn2.setBackground(new java.awt.Color(0, 0, 0));
        addBtn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addBtn2.setForeground(new java.awt.Color(255, 255, 255));
        addBtn2.setText("Add");
        addBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn2ActionPerformed(evt);
            }
        });

        returnBtn.setBackground(new java.awt.Color(0, 0, 0));
        returnBtn.setForeground(new java.awt.Color(255, 255, 255));
        returnBtn.setText("Return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(maxPartLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(durationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(trainerIdLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TrainerIdText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(durationText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxPartText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(IDText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(nameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainerIdLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(TrainerIdText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(durationText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxPartLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(maxPartText))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        label1.getAccessibleContext().setAccessibleName("classIDLbl");
        label3.getAccessibleContext().setAccessibleName("classNameLbl");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTextActionPerformed

    private void IDText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDText1ActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void TrainerIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainerIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrainerIdTextActionPerformed

    private void durationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durationTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_durationTextActionPerformed

    private void maxPartTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxPartTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxPartTextActionPerformed

    private void addBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn2ActionPerformed
        // TODO add your handling code here:
        String name = nameText.getText();
        String ID = IDText.getText();
        String trainerID = TrainerIdText.getText();
        String max = maxPartText.getText();
        String duration = durationText.getText();
        
        if (ID.isEmpty() || name.isEmpty() || trainerID.isEmpty() || max.isEmpty() || duration.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
        else { 
            char[] arr = name.toCharArray();
            for (char i : arr) {
                if (Character.isDigit(i)) {
                    JOptionPane.showMessageDialog(this, "Name shouldn't contain numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
                    return ;
                }
            }
            
            arr = duration.toCharArray();
            for (char i : arr) {
                if (!Character.isDigit(i)) {
                    JOptionPane.showMessageDialog(this, "Duration shouldn't contain letters.", "Input Error", JOptionPane.ERROR_MESSAGE);
                    return ;
                }
            }
            arr = max.toCharArray();
            for (char i : arr) {
                if (!Character.isDigit(i)) {
                    JOptionPane.showMessageDialog(this, "Maximum number shouldn't contain letters.", "Input Error", JOptionPane.ERROR_MESSAGE);
                    return ;
                }
            }
            if (trainerRole.addClass(ID, name, trainerID, Integer.parseInt(duration), Integer.parseInt(max))) {
                JOptionPane.showMessageDialog(this, "Class added successfully.");
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "Class already exists.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addBtn2ActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        TrainerRoleWindow win = new TrainerRoleWindow();
        win.setVisible(true);
    }//GEN-LAST:event_returnBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDText;
    private javax.swing.JTextField IDText1;
    private javax.swing.JTextField TrainerIdText;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addBtn1;
    private javax.swing.JButton addBtn2;
    private java.awt.Label durationLbl;
    private javax.swing.JTextField durationText;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label maxPartLbl;
    private javax.swing.JTextField maxPartText;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton returnBtn;
    private java.awt.Label trainerIdLbl;
    // End of variables declaration//GEN-END:variables
    private void clearFields() {
            IDText.setText("");        
            nameText.setText("");
            maxPartText.setText("");
            durationText.setText("");
            TrainerIdText.setText("");
        }
}
